name: 'Comment Reaction'
description: 'React to a comment within a GitHub Issue or Pull Request'
author: 'Derek Kershner'
inputs:
  token:
    required: true
    description: GitHub token. The standard GITHUB_TOKEN will do just fine.
  commentId:
    required: false
    description: 'The comment ID to react to. Required if the triggering event is not comment related.'
    default: 'The triggering event commentId'
  reaction:
    required: false
    description: 'Must be a valid reaction type: https://docs.github.com/en/rest/reference/reactions#reaction-types'
    default: '+1'
runs:
  using: 'node12'
  main: 'dist/index.js'
